/**
 * Reads .env at project root and writes the EmailJS values into
 * src/environments/environment.ts for local development.
 *
 * Usage: pnpm set-env
 */
import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

// Parse .env
let vars = {};
try {
  const raw = readFileSync(resolve(root, '.env'), 'utf-8');
  for (const line of raw.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const idx = trimmed.indexOf('=');
    if (idx === -1) continue;
    vars[trimmed.slice(0, idx).trim()] = trimmed.slice(idx + 1).trim();
  }
} catch {
  console.error('❌  .env file not found. Create one based on .env.example');
  process.exit(1);
}

const get = (key) => {
  if (!vars[key]) {
    console.error(`❌  Missing key in .env: ${key}`);
    process.exit(1);
  }
  return vars[key];
};

const content = `// Development environment — AUTO-GENERATED by scripts/set-env.mjs
// DO NOT COMMIT this file after running set-env (it will contain real keys).
export const environment = {
  production: false,
  emailjs: {
    publicKey: '${get('EMAILJS_PUBLIC_KEY')}',
    serviceId: '${get('EMAILJS_SERVICE_ID')}',
    templateId: '${get('EMAILJS_TEMPLATE_ID')}',
  },
};
`;

writeFileSync(resolve(root, 'src/environments/environment.ts'), content);
console.log('✅  src/environments/environment.ts updated from .env');
